### ISSUE TITLE
[Mesh] Conflict in use of err_t when building for mesh

### ISSUE THREAD

**Issue by ScruffR** [rickkas7/Adafruit_BLE#2]
As mentioned in this thread, targeting mesh devices (i.e. Boron) causes 
```text
lib/Adafruit_BLE/errors.h:196:3: conflicting declaration ‘typedef enum err_t err_t’
```
https://community.particle.io/t/using-boron-with-adafruit-ble/46297?u=scruffr

**Comment by rickkas7** [comment]
Fixed in version 0.0.3
